config_version = 12

[bar.default]
background_opacity = 0.7
center = [ "workspaces" ]
end = [ "tray", "privacy", "notifications", "network", "bluetooth", "volume", "brightness", "battery", "control-center" ]
font_family = "Inter"
margin_ends = 5
padding = 20
position = "right"
scale = 1.05
start = [ "launcher", "clock", "sysmon", "active_window", "media" ]
thickness = 42
widget_spacing = 16

[control_center]
sidebar_section = "none"
width = 900

[dock]
cross_axis_padding = 0
enabled = true
main_axis_padding = 8
pinned = [ "app.zen_browser.zen", "kitty", "org.gnome.Nautilus", "steam" ]
reserve_space = false
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 376.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.8
        background_padding = 10
        background_radius = 12
        center_text = true
        circle = true
        clock_style = "digital"
        color = "on_surface"
        font_family = ""
        format = "{:%d:%m}, {:%H:%M}"
        shadow = true
        timezone = ""

[nightlight]
enabled = true
force = true
temperature_night = 5500

[notification]
background_opacity = 0.0

[plugins]
auto_update = false
enabled = [ "noctalia/screen_recorder" ]

[shell]
avatar_path = "/home/luks/Documents/dotfiles/avatar.jpg"
clipboard_history_max_entries = 1000
font_family = "Inter"

    [shell.launcher]
    app_grid = true

    [shell.panel]
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"

    [shell.session]
    grid = false

[theme]
builtin = "Kanagawa"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "kitty", "niri" ]

[wallpaper]
directory = "/home/luks/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/luks/Pictures/Wallpapers/forest.jpg"

    [wallpaper.last]
    path = "/home/luks/Pictures/Wallpapers/forest.jpg"

[widget.active_window]
icon_size = 22

[widget.battery]
show_label = false

[widget.brightness]
show_label = false

[widget.clock]
format = "{:%d:%m} - {:%H:%M}"

[widget.launcher]
glyph = "rocket"

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.privacy]
hide_inactive = true

[widget.sysmon]
show_value = false

[widget.volume]
show_label = false
