#!/usr/bin/bash
TEMP=/tmp/current_wall

files=(~/.config/hypr/wallpapers/*)

scripts=~/.config/hypr/scripts


index=$(cat $TEMP)
index=$((index+1))
if [ $index -ge ${#files[@]} ]; then
	index=0
fi
echo $index > $TEMP
$scripts/wall "${files[$index]}"


