#!/usr/bin/bash

# ags
ags &

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# idle manager
swayidle -C $scripts/swayidle &

# initial keyboard layout
echo "English" > ~/.config/hypr/store/current_xkblayout.txt &
notify-send "Keyboard Layout" English &

# wallpaper
$scripts/init_wall $config/wallpapers/space.jpg &

# clipboard history
wl-paste --watch cliphist store &

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
