#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# idle manager
swayidle -C $scripts/swayidle &

# gammastep
gammastep -O 5500 &

# initial keyboard layout
notify-send "Keyboard Layout" English &

# init wallpaper
swww init

# clipboard history
clipse -listen

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# ags
ags &
