map ctrl+p show_scrollback

# map alt+s>t new_tab_with_cwd
# map alt+s>w close_tab
# map alt+s>right next_tab
# map alt+s>left previous_tab
#
# map alt+s>1 goto_tab 1
# map alt+s>2 goto_tab 2
# map alt+s>3 goto_tab 3
# map alt+s>4 goto_tab 4
# map alt+s>5 goto_tab 5
# map alt+s>6 goto_tab 6
# map alt+s>7 goto_tab 7
# map alt+s>8 goto_tab 8
# map alt+s>9 goto_tab 9
#
# map alt+s>% launch --cwd=current --location=vsplit
# map alt+s>" launch --cwd=current --location=hsplit
#
# map alt+left  resize_window narrower 5
# map alt+right resize_window wider 5
# map alt+up    resize_window taller 5
# map alt+down  resize_window shorter 5
#
# map ctrl+left neighboring_window left
# map ctrl+right neighboring_window right
# map ctrl+up neighboring_window up
# map ctrl+down neighboring_window down
