#!/bin/bash

STORE=.store
mkdir -p $STORE

LAYOUT_FILE=$STORE/current_kblayout
touch $LAYOUT_FILE

CURRENT_LAYOUT=$(cat $LAYOUT_FILE)
[[ $CURRENT_LAYOUT = "" ]] && CURRENT_LAYOUT="English"

lang_0=English
lang_1=Português

if [ "$CURRENT_LAYOUT" == $lang_0 ]; then
  CURRENT_LAYOUT=$lang_1
elif [ "$CURRENT_LAYOUT" == $lang_1 ]; then
  CURRENT_LAYOUT=$lang_0
fi

echo "$CURRENT_LAYOUT" > $LAYOUT_FILE

hyprctl switchxkblayout at-translated-set-2-keyboard next

# notify-send "Keyboard Layout" "$CURRENT_LAYOUT"
