#!/bin/bash

STORE=~/.config/hypr/scripts/store
LAYOUT_FILE=$STORE/current_kblayout
CURRENT_LAYOUT=$(cat $LAYOUT_FILE)

lang_0=English
lang_1=Português

if [ "$CURRENT_LAYOUT" == $lang_0 ]; then
  CURRENT_LAYOUT=$lang_1
elif [ "$CURRENT_LAYOUT" == $lang_1 ]; then
  CURRENT_LAYOUT=$lang_0
fi

echo "$CURRENT_LAYOUT" > $LAYOUT_FILE

hyprctl switchxkblayout at-translated-set-2-keyboard next

notify-send "Keyboard Layout" "$CURRENT_LAYOUT"
